# Generated by Django 3.0.6 on 2020-06-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(max_length=100),
        ),
    ]
